version: '3.8'  

services: 
  nostrdvm:  # Name of the service
    build:  
      context: .  
      dockerfile: Dockerfile  
    ports:  
      - "80:80"  
    env_file:
      - .env
    volumes:
      - .:/app  
